site_name: MalOps Agent
site_description: Malware triage agent with FastAPI and multi-agent graph
site_dir: site
docs_dir: docs

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - content.code.copy
    - content.tabs.link
  logo: assets/logo_malops.png
  favicon: assets/logo_malops.png
  palette:
    - scheme: default
      primary: blue
      accent: pink

nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - API: api.md
  - Architecture: architecture.md
  - Reference:
      - API App: reference/api_app.md
      - API Storage: reference/api_storage.md
      - Agent Graph: reference/agent_graph.md
      - Tools: reference/tools.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          # Add project root so modules are imported as `src.*`
          paths: [.] 
          options:
            docstring_style: google
            show_source: true
            show_signature: true
            separate_signature: true
            show_root_heading: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed

extra_javascript:
  # Mermaid for diagrams
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js
